apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# At some point make namespace configurable in overlays
namespace: sso

resources:
- sso.yaml
- openshift-realm.yaml
- openshift-client.yaml
- openshift-user.yaml
- rhsso-openid.yaml
- client-secret.yaml